development:
  min_messages: WARNING
  adapter: postgresql
  host: db
  port: 5432
  encoding: unicode
  database: postgres
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>