#
# Metamaps Dockerfile
#
# https://github.com/metagen/metamaps-docker
#

FROM rails:onbuild

MAINTAINER Daniel Sont "dan.sont@gmail.com"

RUN cp config/database-env.yml config/database.yml

EXPOSE 3000